var sld = '<?xml version="1.0" encoding="ISO-8859-1"?>';
	sld += '<StyledLayerDescriptor version="1.0.0"'; 
	sld += '    xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" ';
	sld += '    xmlns="http://www.opengis.net/sld" ';
	sld += '    xmlns:ogc="http://www.opengis.net/ogc" ';
	sld += '    xmlns:xlink="http://www.w3.org/1999/xlink" ';
	sld += '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">';
	sld += '  <NamedLayer>';
	sld += '    <Name>cite:stateobesity</Name>';
	sld += '    <UserStyle>';
	sld += '      <Title>cite:stateobesity</Title>';
	sld += '      <FeatureTypeStyle>';
	sld += '        <Rule>';
	sld += '          <Name>rate1</Name>';
	sld += '          <Title>Less Than 23.3</Title>';
	sld += '          <ogc:Filter>';
	sld += '            <ogc:PropertyIsLessThan>';
	sld += '              <ogc:PropertyName>obesityR</ogc:PropertyName>';
	sld += '              <ogc:Literal>23.3</ogc:Literal>';
	sld += '            </ogc:PropertyIsLessThan>';
	sld += '          </ogc:Filter>';
	sld += '          <PolygonSymbolizer>';
	sld += '            <Fill>';
	sld += '              <CssParameter name="fill">#edf8fb</CssParameter>';
	sld += '            </Fill>';
	sld += '          </PolygonSymbolizer>';
	sld += '        </Rule>';

	sld += '        <Rule>';
	sld += '          <Name>rate2</Name>';
	sld += '          <Title>23.3 to 27.9</Title>';
	sld += '          <ogc:Filter>';
	sld += '              <ogc:PropertyIsGreaterThanOrEqualTo>';
	sld += '                <ogc:PropertyName>obesityR</ogc:PropertyName>';
	sld += '                <ogc:Literal>23.3</ogc:Literal>';
	sld += '              </ogc:PropertyIsGreaterThanOrEqualTo>';
	sld += '              <ogc:PropertyIsLessThan>';
	sld += '                <ogc:PropertyName>pop</ogc:PropertyName>';
	sld += '                <ogc:Literal>27.9</ogc:Literal>';
	sld += '              </ogc:PropertyIsLessThan>';
	sld += '          </ogc:Filter>';
	sld += '          <PolygonSymbolizer>';
	sld += '            <Fill>';
	sld += '              <CssParameter name="fill">#b2e2e2</CssParameter>';
	sld += '            </Fill>';
	sld += '          </PolygonSymbolizer>';
	sld += '        </Rule>';

	sld += '        <Rule>';
	sld += '          <Name>rate3</Name>';
	sld += '          <Title>27.9 to 30.5</Title>';
	sld += '          <ogc:Filter>';
	sld += '              <ogc:PropertyIsGreaterThanOrEqualTo>';
	sld += '                <ogc:PropertyName>obesityR</ogc:PropertyName>';
	sld += '                <ogc:Literal>27.9</ogc:Literal>';
	sld += '              </ogc:PropertyIsGreaterThanOrEqualTo>';
	sld += '              <ogc:PropertyIsLessThan>';
	sld += '                <ogc:PropertyName>pop</ogc:PropertyName>';
	sld += '                <ogc:Literal>30.5</ogc:Literal>';
	sld += '              </ogc:PropertyIsLessThan>';
	sld += '          </ogc:Filter>';
	sld += '          <PolygonSymbolizer>';
	sld += '            <Fill>';
	sld += '              <CssParameter name="fill">#66c2a4</CssParameter>';
	sld += '            </Fill>';
	sld += '          </PolygonSymbolizer>';
	sld += '        </Rule>';

	sld += '        <Rule>';
	sld += '          <Name>rate4</Name>';
	sld += '          <Title>30.5 to 33.5</Title>';
	sld += '          <ogc:Filter>';
	sld += '              <ogc:PropertyIsGreaterThanOrEqualTo>';
	sld += '                <ogc:PropertyName>obesityR</ogc:PropertyName>';
	sld += '                <ogc:Literal>30.5</ogc:Literal>';
	sld += '              </ogc:PropertyIsGreaterThanOrEqualTo>';
	sld += '              <ogc:PropertyIsLessThan>';
	sld += '                <ogc:PropertyName>pop</ogc:PropertyName>';
	sld += '                <ogc:Literal>33.5</ogc:Literal>';
	sld += '              </ogc:PropertyIsLessThan>';
	sld += '          </ogc:Filter>';
	sld += '          <PolygonSymbolizer>';
	sld += '            <Fill>';
	sld += '              <CssParameter name="fill">#2ca25f</CssParameter>';
	sld += '            </Fill>';
	sld += '          </PolygonSymbolizer>';
	sld += '        </Rule>';

	sld += '        <Rule>';
	sld += '          <Name>rate5</Name>';
	sld += '          <Title>Greater Than 33.5</Title>';
	sld += '          <ogc:Filter>';
	sld += '            <ogc:PropertyIsGreaterThan>';
	sld += '              <ogc:PropertyName>obesityR</ogc:PropertyName>';
	sld += '              <ogc:Literal>33.5</ogc:Literal>';
	sld += '            </ogc:PropertyIsGreaterThan>';
	sld += '          </ogc:Filter>';
	sld += '          <PolygonSymbolizer>';
	sld += '            <Fill>';
	sld += '              <CssParameter name="fill">#006d2c</CssParameter>';
	sld += '            </Fill>';
	sld += '          </PolygonSymbolizer>';
	sld += '        </Rule>';
	sld += '      </FeatureTypeStyle>';
	sld += '    </UserStyle>';
	sld += '  </NamedLayer>';
	sld += '</StyledLayerDescriptor>';